export const defaultData = {
  businesses: [
    {
      id: 'biz_fitpro',
      name: 'FitPro Gym',
      email: 'admin@fitpro.gym',
      password: 'demo123',
      ownerName: 'Admin',
      createdAt: '2025-01-15',
    },
  ],
  currentBusinessId: null,
  plans: {
    biz_fitpro: [
      {
        id: 'plan_1',
        name: 'Monthly Basic',
        price: 999,
        interval: 'monthly',
        description: 'Access to gym floor & locker',
        features: ['Gym floor access', 'Locker', 'Basic support'],
        active: true,
      },
      {
        id: 'plan_2',
        name: 'Monthly Premium',
        price: 1999,
        interval: 'monthly',
        description: 'Full access + classes + PT discount',
        features: ['All gym access', 'Group classes', '10% PT discount', 'Priority support'],
        active: true,
      },
      {
        id: 'plan_3',
        name: 'Yearly Gold',
        price: 18999,
        interval: 'yearly',
        description: 'Best value annual membership',
        features: ['All Premium benefits', '2 free PT sessions', 'Guest passes', 'Free merchandise'],
        active: true,
      },
      {
        id: 'plan_4',
        name: 'Quarterly Flex',
        price: 5499,
        interval: 'quarterly',
        description: 'Flexible 3-month plan',
        features: ['Gym + classes', 'Freeze option', 'Email support'],
        active: true,
      },
    ],
  },
  customers: {
    biz_fitpro: [
      {
        id: 'cust_1',
        name: 'Vinit Kumar',
        email: 'vinitkumar@gmail.com',
        phone: '+91 98765 43210',
        status: 'active',
        joinDate: '2025-03-12',
        notes: 'Prefers morning slots',
      },
      {
        id: 'cust_2',
        name: 'Shoaib Akhtar',
        email: 'shoaibakhtar14022002@gmail.com',
        phone: '+91 91234 56789',
        status: 'active',
        joinDate: '2025-05-20',
        notes: '',
      },
      {
        id: 'cust_3',
        name: 'Aqbal Ahmad',
        email: 'aqbalahmad09@email.com',
        phone: '+91 99887 76655',
        status: 'active',
        joinDate: '2025-01-08',
        notes: 'Corporate membership',
      },
      {
        id: 'cust_4',
        name: 'Md Sarfraz',
        email: 'sarfraz11@email.com',
        phone: '+91 97654 32109',
        status: 'inactive',
        joinDate: '2024-11-15',
        notes: 'Moved to another city',
      },
      {
        id: 'cust_5',
        name: 'Piyush Raj',
        email: 'piyush@email.com',
        phone: '+91 96543 21098',
        status: 'active',
        joinDate: '2025-06-01',
        notes: '',
      },
      {
        id: 'cust_6',
        name: 'Mahwish',
        email: 'mahwish@gmail.com',
        phone: '+91 95432 10987',
        status: 'active',
        joinDate: '2025-02-28',
        notes: 'Yoga enthusiast',
      },
      {
        id: 'cust_7',
        name: 'Milind Suman',
        email: 'milind@gmail.com',
        phone: '+91 94321 09876',
        status: 'churned',
        joinDate: '2024-09-10',
        notes: 'Cancelled due to price',
      },
      {
        id: 'cust_8',
        name: 'Pratibha',
        email: 'pratibha@email.com',
        phone: '+91 93210 98765',
        status: 'active',
        joinDate: '2025-07-15',
        notes: '',
      },
    ],
  },
  subscriptions: {
    biz_fitpro: [
      {
        id: 'sub_1',
        customerId: 'cust_1',
        planId: 'plan_2',
        status: 'active',
        startDate: '2025-03-12',
        endDate: '2026-03-12',
        nextRenewal: '2026-03-12',
        amount: 1999,
        autoRenew: true,
      },
      {
        id: 'sub_2',
        customerId: 'cust_2',
        planId: 'plan_1',
        status: 'active',
        startDate: '2025-05-20',
        endDate: '2025-09-20',
        nextRenewal: '2025-09-20',
        amount: 999,
        autoRenew: true,
      },
      {
        id: 'sub_3',
        customerId: 'cust_3',
        planId: 'plan_3',
        status: 'active',
        startDate: '2025-01-08',
        endDate: '2026-01-08',
        nextRenewal: '2026-01-08',
        amount: 18999,
        autoRenew: true,
      },
      {
        id: 'sub_4',
        customerId: 'cust_4',
        planId: 'plan_1',
        status: 'cancelled',
        startDate: '2024-11-15',
        endDate: '2025-02-15',
        nextRenewal: null,
        amount: 999,
        autoRenew: false,
      },
      {
        id: 'sub_5',
        customerId: 'cust_5',
        planId: 'plan_2',
        status: 'active',
        startDate: '2025-06-01',
        endDate: '2025-09-01',
        nextRenewal: '2025-09-01',
        amount: 1999,
        autoRenew: true,
      },
      {
        id: 'sub_6',
        customerId: 'cust_6',
        planId: 'plan_4',
        status: 'active',
        startDate: '2025-02-28',
        endDate: '2025-08-28',
        nextRenewal: '2025-08-28',
        amount: 5499,
        autoRenew: false,
      },
      {
        id: 'sub_7',
        customerId: 'cust_7',
        planId: 'plan_2',
        status: 'cancelled',
        startDate: '2024-09-10',
        endDate: '2024-12-10',
        nextRenewal: null,
        amount: 1999,
        autoRenew: false,
      },
      {
        id: 'sub_8',
        customerId: 'cust_8',
        planId: 'plan_1',
        status: 'active',
        startDate: '2025-07-15',
        endDate: '2025-08-15',
        nextRenewal: '2025-08-15',
        amount: 999,
        autoRenew: true,
      },
      {
        id: 'sub_9',
        customerId: 'cust_1',
        planId: 'plan_1',
        status: 'expired',
        startDate: '2024-03-12',
        endDate: '2025-03-12',
        nextRenewal: null,
        amount: 999,
        autoRenew: false,
      },
    ],
  },
  invoices: {
    biz_fitpro: [
      {
        id: 'inv_1',
        customerId: 'cust_1',
        subscriptionId: 'sub_1',
        amount: 1999,
        status: 'paid',
        dueDate: '2025-03-12',
        paidDate: '2025-03-11',
        invoiceNumber: 'INV-2025-001',
      },
      {
        id: 'inv_2',
        customerId: 'cust_2',
        subscriptionId: 'sub_2',
        amount: 999,
        status: 'paid',
        dueDate: '2025-05-20',
        paidDate: '2025-05-20',
        invoiceNumber: 'INV-2025-002',
      },
      {
        id: 'inv_3',
        customerId: 'cust_3',
        subscriptionId: 'sub_3',
        amount: 18999,
        status: 'paid',
        dueDate: '2025-01-08',
        paidDate: '2025-01-07',
        invoiceNumber: 'INV-2025-003',
      },
      {
        id: 'inv_4',
        customerId: 'cust_5',
        subscriptionId: 'sub_5',
        amount: 1999,
        status: 'paid',
        dueDate: '2025-06-01',
        paidDate: '2025-06-01',
        invoiceNumber: 'INV-2025-004',
      },
      {
        id: 'inv_5',
        customerId: 'cust_6',
        subscriptionId: 'sub_6',
        amount: 5499,
        status: 'paid',
        dueDate: '2025-02-28',
        paidDate: '2025-02-28',
        invoiceNumber: 'INV-2025-005',
      },
      {
        id: 'inv_6',
        customerId: 'cust_8',
        subscriptionId: 'sub_8',
        amount: 999,
        status: 'pending',
        dueDate: '2025-08-15',
        paidDate: null,
        invoiceNumber: 'INV-2025-006',
      },
      {
        id: 'inv_7',
        customerId: 'cust_2',
        subscriptionId: 'sub_2',
        amount: 999,
        status: 'overdue',
        dueDate: '2025-08-20',
        paidDate: null,
        invoiceNumber: 'INV-2025-007',
      },
      {
        id: 'inv_8',
        customerId: 'cust_5',
        subscriptionId: 'sub_5',
        amount: 1999,
        status: 'pending',
        dueDate: '2025-09-01',
        paidDate: null,
        invoiceNumber: 'INV-2025-008',
      },
    ],
  },
}